[tool.poetry]
name = "mental health chat bot"
version = "0.1.0"
description = ""
authors = ["ivan golt"]

[tool.poetry.dependencies]
python = "^3.10"
transformers = "^4.44.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
